### ISSUE TITLE
Can't export full collection

### ISSUE THREAD

**Issue by BobSpan** [matt-h/rdio-enhancer#38]
Can't see a way to export csv for full collection since Rdio redesign.

**Comment by BobSpan** [comment]
Matt, sorry for not acknowledging earlier (was using the API), thanks for fixing this. Great to able to use enhancer again.

**Comment by jabalong** [comment]
Strange timing, but the "Export to CSV" option has stopped working for me yesterday.

Well, at least yesterday was the first day I noticed the problem (last successful use was 8 Feb).

Am getting this error:

“There was an error getting the Favorites data, if you have a large amount of favorites try scrolling down to load more first and then try the action again.”

First time I've seen this error (using extension since last Jun).

Tried scrolling through list to no avail. 

Have about 5,000 favorites (large amount?), but this number hasn't changed much in a while, so don't know why it would suddenly be a problem.

Am using latest version of rdio-enhancer (2.8.3) and Chrome (40.0.2214.115).

Any thoughts?
